[package]
name = "rust-bitcoin-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
reqwest-wasm = "0.11.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen-futures = "0.4.50"

[lib]
crate-type = ["cdylib", "rlib"]
